### ISSUE TITLE
Melior unable to find LLVM/MLIR-17

### ISSUE THREAD

**Issue by ctrlv0** [mlir-rs/melior#502]
when i try to use melior 0.17.0 in my project on wsl (ubuntu 20.04.6) it gives me an error saying
`failed to find correct version (17.x.x) of llvm-config (found )`

However, i have LLVM/MLIR-17 installed and inkwell seems to work without no problems.

`llvm-config-17` command is exposed to bash and can be invoked from any path.

what am i doing wrong here?

**Comment by raviqqe** [comment]
I think it's because Ubuntu somehow puts all LLVM tools' names with a `-17` suffix. This is more like an issue of https://github.com/femtomc/mlir-sys.

**Comment by raviqqe** [comment]
@ctrlv0 If you still have this issue, please post it on mlir-rs/mlir-sys!
